export const elements = {

    searchbar: '.search',
    searchedProductLink: 'a.product-item-link',
    customerName: '.customer-name',
    errorMessage: '.message-error.error.message',
    size: '.swatch-option.text',
    color: '.swatch-option.color',
    price: '.price-wrapper',
    quantity: '#qty',
    addToCart: '#product-addtocart-button',
    showCart: '.showcart',
    viewcart: '.viewcart',
    pageTitle: '.page-title-wrapper',
    productName: '.product-item-name',
    cartPrice: '.cart-price',
    cartQuantity: '[title="Qty"]',
    removeItem: '.action-delete',
    emptyMessage: '.cart-empty',

    firstName: '#firstname',
    lastName: '#lastname',
    emailForSignIn: '#email_address',
    passwordForSignIn: '#password',
    confirmPassword: '#password-confirmation',
    createAnAccount: '[title="Create an Account"]',
    link: 'a',

    emailForLogIn: '#email',
    passwordForLogIn: '#pass',
    loginButton: '#send2',
}